version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      dev-dependencies:
        patterns:
          - "ruff"
          - "mypy"
          - "pytest*"
          - "bandit"
          - "radon"
          - "pre-commit"
          - "respx"
          - "types-*"
      security:
        patterns:
          - "bandit"
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
